#!/bin/sh

### BEGIN INIT INFO
# Provides:		apcupsd
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Should-Start:		$local_fs
# Should-Stop:		$local_fs
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description:	Starts apcupsd daemon
# Description:		apcupsd provides UPS power management for APC products.
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/sbin/apcupsd
CONFIG=/etc/default/apcupsd
NAME=apcupsd
DESC="UPS power management"

test -x $DAEMON || exit 0
test -e $CONFIG || exit 0

set -e

. $CONFIG

if [ "x$ISCONFIGURED" != "xyes" ] ;
then
	echo "Please check your configuration ISCONFIGURED in /etc/default/apcupsd"
	exit 0
fi


case "$1" in
	start)
                echo -n "Starting $DESC: "

                /usr/bin/find /etc/apcupsd -name powerfail -exec /bin/rm {} \;
                /bin/rm -f /var/lock/apcupsd.doshutdown.*

                if [ "`pidof apcupsd`" = "" ]
                then
                        for CONF in /etc/apcupsd/apcupsd*.conf; do
                                UPSNAME=`grep UPSNAME $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
                                PWRFAILDIR=`grep PWRFAILDIR $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
                                NISIP=`grep NISIP $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
                                NISPORT=`grep NISPORT $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
                                /usr/bin/touch $PWRFAILDIR/powerfail
                                while [ -e $PWRFAILDIR/powerfail ]; do
                                        echo -n "Starting UPS monitoring ($UPSNAME):"
                                        $DAEMON -f $CONF -P /var/run/apcupsd.$UPSNAME.pid; sleep 20
                                        if ( /sbin/apcaccess status $NISIP:$NISPORT 2>/dev/null | grep STATUS | grep -q 'ONLINE\|ONBATT' )
                                        then /bin/rm $PWRFAILDIR/powerfail
                                        else
                                                if [ `ps aux | grep $NAME | grep -v grep | grep apcupsd.$UPSNAME.pid | grep $CONF | awk '{print $2}'` ]
                                                then until /bin/kill -15 `ps aux | grep $NAME | grep -v grep | grep apcupsd.$UPSNAME.pid | grep $CONF | awk '{print $2}'`; do sleep 1; done
                                                fi
                                        fi
                                done &
                        done
                else
                        echo ""
                        echo "A copy of the daemon is still running.  If you just stopped it,"
                        echo "please wait about 5 seconds for it to shut down."
                        exit 0
                fi
                ;;
	
	stop)
                        for CONF in /etc/apcupsd/apcupsd*.conf; do
                        UPSNAME=`grep UPSNAME $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
                        if [ `ps aux | grep apcupsd | grep -v grep | grep $UPSNAME | grep $CONF | awk '{print $2}'` ]
                              then until /bin/kill -15 `ps aux | grep apcupsd | grep -v grep | grep $UPSNAME | grep $CONF | awk '{print $2}'`; do sleep 1; done
                        fi
                        echo -n "Stopping $DESC: "
                        rm -f /var/run/apcupsd.$UPSNAME.pid
                        echo "$NAME.$UPSNAME"
                        done
                ;;

	restart|force-reload)
		$0 stop
		sleep 10
		$0 start
		;;

	status)
		#/sbin/apcaccess status
		for CONF in `ls /etc/apcupsd/apcupsd*.conf`; do
		NISIP=`grep NISIP $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
		NISPORT=`grep NISPORT $CONF | sed 's/^[ \t]*//' | grep -v ^# | awk '{print $2}'`
                        $APCACCESS status $NISIP:$NISPORT
                done
		;;

	*)
		N=/etc/init.d/$NAME
		echo "Usage: $N {start|stop|restart|force-reload}" >&2
		exit 1
		;;
esac

exit 0
