#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when apcupsd
# loses contact with the UPS (i.e. the serial connection is not responding).
# We send an email message to root to notify him.
#
SYSADMIN=root
APCUPSD_MAIL="mail"
UPSNAME=$1

HOSTNAME=`hostname`
MSG="$HOSTNAME $UPSNAME Communications with UPS lost"
#
(
   echo "Subject: $MSG"
   echo " "
   echo "$MSG"
) | $APCUPSD_MAIL -s "$MSG" $SYSADMIN
exit 0
